### ISSUE TITLE
Support labels as an exclusion rule 

### ISSUE THREAD

**Issue by s4heid** [s4heid/branch-switcher#3]
When opening a pull request with a specific label (e.g., `ignore-branch`) against a non-preferred branch, I'd expect that the base branch of the pull request will not be changed to the preferred.

Example config file:
```yaml
excludeLabel: ignore-branch
```

After #2 is done, the config structure could also be like this:
```yaml
exclude:
  labels:
    - ignore-branch
  branches:
    - master
    - rel-*
```

**Comment by dpb587-pivotal** [comment]
Another format to consider for the config structure...

```yaml
exclude:
- label: ignore-branch
- branch: master
- branch: rel-*
```
